redirect errors to stderr

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -6,14 +6,14 @@ readonly BUILD_DIR=$1
 readonly CLEAN_FILES=.slug-post-clean
 
 if [[ ! -n "${BUILD_DIR}" ]]; then
-  echo "No build directory specified - exiting"
+  echo "No build directory specified - exiting" >&2
   exit 1
 fi
 
 cd ${BUILD_DIR}
 
 if [[ ! -f "${CLEAN_FILES}" ]]; then
-  echo "Could not find .slug-post-clean file - exiting"
+  echo "Could not find .slug-post-clean file - exiting" >&2
   exit 1
 fi
 
diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -5,11 +5,11 @@ set -euo pipefail
 readonly BUILD_DIR=$1
 
 if [[ ! -n "${BUILD_DIR}" ]]; then
-  echo "No build directory specified - exiting"
+  echo "No build directory specified - exiting" >&2
   exit 1
 fi
 
 if [[ ! -f "${BUILD_DIR}/.slug-post-clean" ]]; then
-  echo "Could not find .slug-post-clean file - exiting"
+  echo "Could not find .slug-post-clean file - exiting" >&2
   exit 1
 fi
